AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5.1
  Exclude:
    - '**/bin/spring'
    - '**/bin/setup'
    - '**/bin/rake'
    - '**/bin/rails'
    - '**/db/schema.rb'
    - 'client/**/**'
    - 'config/**/**'
    - 'db/**/**'
    - 'bin/**'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

Metrics/AbcSize:
  Max: 30

Style/Documentation:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
  ExcludedMethods: ['included']

Rails/SkipsModelValidations:
  Exclude:
    - '**/*_spec.rb'
