AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  RunRailsCops: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - '**/bin/spring'
    - '**/bin/setup'
    - '**/bin/rake'
    - '**/bin/rails'
    - '**/db/schema.rb'
    - 'client/**/**'
    - 'config/**/**'
    - 'db/**/**'
    - 'bin/**'
    - 'app/models/role.rb'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

Metrics/AbcSize:
  Max: 30

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/DeprecatedHashMethods:
  Enabled: false

Style/ParenthesesAroundCondition:
  AllowSafeAssignment: false
Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Style/RaiseArgs:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Style/Documentation:
  Enabled: false 

Style/OpMethod:
  Enabled: false 

Lint/Debugger:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
